### ISSUE TITLE
instal point to wrong github repo

### ISSUE THREAD

**Issue by adugourd** [EPFL-LCSB/redgem#1]
Hi :)

Just wanted to point that the install is pointing to the wrong repo: 

git clone https://github.com/EPFL-LCSB/redhuman.git /path/to/redhuman

Should be:

git clone https://github.com/EPFL-LCSB/redgem.git /path/to/redGEM

**Comment by MariaMasid** [comment]
Hi :)

Thank you very much, Aurelien! I have corrected it
